name: CMake SKSE Setup

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: Make_Them_Slow_or_Fast
  PROJECT_VERSION: 1.1.0.3


jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: lukka/get-cmake@latest

    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

    - name: Configure and Run CMake Preset for "Debug" preset
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'Debug'
        buildPreset: 'Debug'

    - name: Configure and Run CMake Preset for "Release" preset
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'Release'
        buildPreset: 'Release'

    - name: Deploy Aritfact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ${{ github.workspace }}/contrib/Artifact/${{ env.PROJECT_NAME }}_${{ env.PROJECT_VERSION }}.7z

    - name: Upload files to a GitHub release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ github.workspace }}/contrib/Artifact/${{ env.PROJECT_NAME }}_${{ env.PROJECT_VERSION }}.7z
        tag: ${{ env.PROJECT_VERSION }}
        commit: main
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
        makeLatest: "latest"
        name: ${{ env.PROJECT_NAME }} ${{ env.PROJECT_VERSION }}
